#!/bin/sh
# Swingflip - HakchiResources.com https://discord.gg/8gygsrw

    start()
    {

        source /etc/preinit
        script_init

        [ -f "/media/hakchi/retroarch-mounted.cfg" ] && mv -f "/media/hakchi/retroarch-mounted.cfg" "/etc/libretro/"
        [ -f "/media/hakchi/network-mount.cfg" ] && mv -f "/media/hakchi/network-mount.cfg" "/etc/"

        if [ -f "/etc/network-mount.cfg" ]; then #Just incase some one fucks up
        
            source /etc/network-mount.cfg
            [ "$mount_use_ra_cfg" == "true" ] && source /etc/libretro/retroarch-mounted.cfg
            
            trueip="$(echo "$ra_mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
            i=1
            while [ "$i" -le 60 ]; do #60 Second Ping test
              echo "Ping Test Number $i against IP address: $trueip" > /dev/tty0
              ping -c 1 "$trueip"
              rc=$?
              sleep 1
              if [ $rc = 0 ] ; then
                echo "Ping Test Success!" > /dev/tty0
                i=666
              else
                i="$((i+1))"
              fi
            done
            [ $rc = 0 ] || exit 1
            
            if [ "$ra_mount_enable" == "true" ] && [ ! -z "${ra_mount_address// }" ] || [ "$mount_enable" == "true" ] && [ ! -z "${mount_address// }" ]; then
                mkdir -p -v /var/mount &> /dev/tty0
                if [ "$ra_mount_enable" == "true" ]; then
                    if [ "$ra_mount_vers" -gt "0" ]; then
                        mount -t cifs -o user=$ra_mount_user,pass=$ra_mount_pass,vers=$ra_mount_vers.0 $ra_mount_address /var/mount &> /dev/tty0
                    else
                        mount -t cifs -o user=$ra_mount_user,pass=$ra_mount_pass $ra_mount_address /var/mount &> /dev/tty0
                    fi
                else
                    if [ "$mount_vers" -gt "0" ]; then
                        mount -t cifs -o user=$mount_user,pass=$mount_pass,vers=$mount_vers.0 $mount_address /var/mount &> /dev/tty0
                    else
                        mount -t cifs -o user=$mount_user,pass=$mount_pass $mount_address /var/mount &> /dev/tty0
                    fi
                fi
            fi
            
            if mountpoint -q /var/mount; then #If false, we fucked up.
                echo "[NetMount] Mounted network drive" &> /dev/tty0
                if [ "$mount_saves" == "true" ]; then
                    [ ! -d "/var/mount/saves" ] && mkdir -p /var/mount/saves 
                    echo "[NetMount] Mounted saves on network share" &> /dev/tty0
                    #Overmount something && echo "[NetMount] Mounted saves on network share"
                fi
                if [ ! -d "/var/mount/games" ]; then
                    echo "[NetMount] Mounted games on network share" &> /dev/tty0
                    #Overmount something && echo "[NetMount] Mounted games on network share"
                fi
            else
                echo "[NetMount] [FAIL] Failed to mount network!" &> /dev/tty0
            fi
        fi
        
        clear > /dev/tty0

    }

    stop()
    {
        if [ -d /var/mount ]; then
            [ "$mount_saves" == "true" ] && umount "/var/mount/saves"
            [ ! -d "/var/mount/games" ] && umount "/var/mount/games"
            umount "/var/mount"
            rm -rf "/var/mount" 
            echo "[NetMount] Unmounted network drive"
        fi
    }

    case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Network mount script: Does some cool shit..."
        exit 1
    esac