#!/bin/sh
# Swingflip - HakchiResources.com https://discord.gg/8gygsrw

    start()
    {
		
        source /etc/preinit
        script_init
        
        # Reset
        Color_Off="\e[33;0m"       # Text Reset
		
        # Regular Colors
        Black="\e[33;0;30m"        # Black
        Red="\e[33;0;31m"          # Red
        Green="\e[33;0;32m"        # Green
        Yellow="\e[33;0;33m"       # Yellow
        Blue="\e[33;0;34m"         # Blue
        Purple="\e[33;0;35m"       # Purple
        Cyan="\e[33;0;36m"         # Cyan
        White="\e[33;0;37m"        # White
		
        [ -f "/media/hakchi/retroarch-mounted.cfg" ] && mv -f "/media/hakchi/retroarch-mounted.cfg" "/etc/libretro/"
        [ -f "/media/hakchi/network-mount.cfg" ] && mv -f "/media/hakchi/network-mount.cfg" "/etc/"
		
		source /etc/network-mount.cfg
        [ "$mount_use_ra_cfg" == "true" ] && source /etc/libretro/retroarch-mounted.cfg
        
		if [ -f "/etc/network-mount.cfg" ]; then #Just incase some one fucks up
            
            if ([ "$ra_mount_enable" == "true" ] && [ ! -z "${ra_mount_address// }" ]) || ([ "$mount_enable" == "true" ] && [ ! -z "${mount_address// }" ]); then
				
                echo -e "${Green}***************************" > /dev/tty0
                echo -e "${Green}***Hakchi Networking Mod***" > /dev/tty0
                echo -e "${Green}***************************" > /dev/tty0
				
                if [ "$mount_use_ra_cfg" == "true" ]; then
                  trueip="$(echo "$ra_mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
                else
                  trueip="$(echo "$mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
                fi
                
                echo -e "${White}Connecting to${Yellow} $trueip...${White}" > /dev/tty0
				
                until ping -w 1 -c 1 "$trueip" > /dev/tty0; do
                  [ "$(cat /dev/clovercon1)" = "0800" ] && exit 1
                  ping_loop="$((ping_loop+1))"
                  echo "Connection Attempt $ping_loop/30" > /dev/tty0
                  [ "$ping_loop" -ge "30" ] && exit 1
                  sleep 1
                done
                echo -e "${Green}Connected to network!${White}" > /dev/tty0
				
                mkdir -p -v /var/mount &> /dev/tty0
                if [ "$ra_mount_enable" == "true" ]; then
                    if [ "$ra_mount_vers" -gt "0" ]; then
                        mount -t cifs -o user=$ra_mount_user,pass=$ra_mount_pass,vers=$ra_mount_vers.0 $ra_mount_address /var/mount &> /dev/tty0
                    else
                        mount -t cifs -o user=$ra_mount_user,pass=$ra_mount_pass $ra_mount_address /var/mount &> /dev/tty0
                    fi
                else
                    if [ "$mount_vers" -gt "0" ]; then
                        mount -t cifs -o user=$mount_user,pass=$mount_pass,vers=$mount_vers.0 $mount_address /var/mount &> /dev/tty0
                    else
                        mount -t cifs -o user=$mount_user,pass=$mount_pass $mount_address /var/mount &> /dev/tty0
                    fi
                fi
            fi
			
            if mountpoint -q /var/mount; then #If false, we fucked up.
                echo -e "${Green}[NetMount] Mounted network drive" &> /dev/tty0
                if [ "$mount_saves" == "true" ]; then
                    [ ! -d "/var/mount/saves" ] && mkdir -p /var/mount/saves 
                    echo -e "{Green}[NetMount] Mounted saves on network share${Color_Off}" &> /dev/tty0
                    #Overmount something && echo "[NetMount] Mounted saves on network share"
                fi
                if [ ! -d "/var/mount/games" ]; then
                    echo -e "{Green}[NetMount] Mounted games on network share${Color_Off}" &> /dev/tty0
                    #Overmount something && echo "[NetMount] Mounted games on network share"
                fi
            else
                echo -e "${Red}[NetMount] [FAIL] Failed to mount network!${Color_Off}" &> /dev/tty0
            fi
        fi
        
        clear > /dev/tty0
	
    }

    stop()
    {
        if [ -d /var/mount ]; then
            [ "$mount_saves" == "true" ] && umount "/var/mount/saves"
            [ ! -d "/var/mount/games" ] && umount "/var/mount/games"
            umount "/var/mount"
            rm -rf "/var/mount" 
            echo "[NetMount] Unmounted network drive"
        fi
    }

    case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Network mount script: Does some cool shit..."
        exit 1
    esac